#!/bin/bash

DIR="x264-$ARCH"

git clone git://git.videolan.org/x264.git $DIR

cd $DIR
mkdir -p dist

case $ARCH in
    i386)
        CC=/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/i686-apple-darwin10-gcc-4.2.1
        SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk
        ;;
    *)
        CC=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2
        SYSROOT=/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.0.sdk
        ;;
esac

CC=$CC ./configure $EXTRA_FLAGS --sysroot="$SYSROOT" --prefix='dist' --extra-cflags="$EXTRA_CFLAGS" --extra-ldflags="$EXTRA_LDFLAGS"

make && make install

echo "Installed: $DIR/dist"
