#!/bin/bash

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common

rm -rf lame-3.98.4 lame
if [ ! -f lame-3.98.4.tar.gz ]
then
    wget -q 'http://downloads.sourceforge.net/project/lame/lame/3.98.4/lame-3.98.4.tar.gz'
fi
tar zxf lame-3.98.4.tar.gz
mv lame-3.98.4 lame


for ARCH in $ARCHS
do
    DIR="lame-$ARCH"
    rm -rf $DIR
    cp -a lame $DIR

    cd $DIR
    DIST_DIR=$DIST_DIR_BASE-$ARCH
    mkdir -p $DIST_DIR

    EXTRA_CFLAGS="-arch $ARCH --sysroot=$SYSROOT"
    EXTRA_LDFLAGS="-arch $ARCH --sysroot=$SYSROOT"
    case $ARCH in
        armv6)
            EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic --disable-asm"
            ;;
        armv7)
            EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic"
            ;;
        i386)
            ;;
    esac

    echo "Configuring lame for $ARCH..."
    CC=$CC CPP=$CPP ./configure CFLAGS="$EXTRA_CFLAGS" LDFLAGS="$EXTRA_LDFLAGS" --prefix=$DIST_DIR --disable-shared $EXTRA_FLAGS $LIB_FLAGS --disable-frontend

    echo "Installing lame for $ARCH..."
    make && make install

    cd $SCRIPT_DIR
done
