#!/bin/bash

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common

rm -rf libogg-1.2.0 ogg
if [ ! -f libogg-1.2.0.tar.gz ]
then
    wget -q http://downloads.xiph.org/releases/ogg/libogg-1.2.0.tar.gz
fi
tar zxf libogg-1.2.0.tar.gz
mv libogg-1.2.0 ogg

rm -rf vorbis libvorbis-1.3.1
if [ ! -f libvorbis-1.3.1.tar.gz ]
then
    wget -q http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.1.tar.gz
fi
tar zxf libvorbis-1.3.1.tar.gz
mv libvorbis-1.3.1 vorbis

LIBS="ogg vorbis"

for ARCH in $ARCHS
do

    for LIB in $LIBS
    do
        DIR="$LIB-$ARCH"
        cp -a $LIB $DIR

        cd $DIR
        mkdir -p dist

        EXTRA_CFLAGS="-arch $ARCH --sysroot=$SYSROOT"
        EXTRA_LDFLAGS="-arch $ARCH --sysroot=$SYSROOT"
        case $ARCH in
            armv6)
                EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic --disable-asm"
                ;;
            armv7)
                EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic"
                ;;
            i386)
                ;;
        esac

        case $LIB in
            vorbis)
                LIB_FLAGS="--disable-oggtest"
                export OGG_CFLAGS="-I`pwd`/../ogg-$ARCH/dist/include"
                ;;
        esac

        echo "Configuring $LIB for $ARCH..."
        CC=$CC CPP=$CPP ./configure CFLAGS="$EXTRA_CFLAGS" LDFLAGS="$EXTRA_LDFLAGS" --prefix=`pwd`/dist --disable-shared $EXTRA_FLAGS $LIB_FLAGS

        # Make it not compile
        case $LIB in
            vorbis)
                touch lib/test_sharedbook
                ;;
        esac

        echo "Compiling $LIB for $ARCH..."
        make && make install

        echo "Installed: $DIR/dist"
        cd $SCRIPT_DIR
    done
done
