#!/bin/bash

ARCHS=${ARCHS:-"armv6 armv7 i386"}

PATH=$SCRIPT_DIR:$PATH

case $ARCH in
    i386)
        CC=/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/i686-apple-darwin10-gcc-4.2.1
        SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk
        ;;
    *)
        CC=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2
        SYSROOT=/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.0.sdk
        ;;
esac
AS=$CC
NM=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/nm


# Override any of the above locally
if [ -f $SCRIPT_DIR/build-local ]
then
    . $SCRIPT_DIR/build-local
fi
