#!/bin/bash

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common

rm -rf libvpx-0.9.1 vpx
if [ ! -f libvpx-0.9.1.tar.bz2 ]
then
    wget -q http://webm.googlecode.com/files/libvpx-0.9.1.tar.bz2
fi
tar jxf libvpx-0.9.1.tar.bz2
mv libvpx-0.9.1 vpx


for ARCH in $ARCHS
do
    DIR="vpx-$ARCH"
    rm -rf $DIR
    cp -a vpx $DIR

    cd $DIR
    mkdir -p dist

    sed "s/iPhoneOS3.1/iPhoneOS$SDK_VERSION/;s/arm-apple-darwin9-gcc-4.2.1/gcc/" < build/make/configure.sh > build/make/configure.sh.tmp && mv build/make/configure.sh.tmp build/make/configure.sh
    chmod +x build/make/configure.sh

    EXTRA_CFLAGS="-arch $ARCH --sysroot=$SYSROOT"
    EXTRA_LDFLAGS="-arch $ARCH --sysroot=$SYSROOT"
    case $ARCH in
        armv6)
            EXTRA_FLAGS="--target=armv6-darwin-gcc"
            ;;
        armv7)
            EXTRA_FLAGS="--target=armv7-darwin-gcc"
            ;;
        i386)
            ;;
    esac

    echo "Configuring vpx for $ARCH..."
    CC=$CC CFLAGS="$EXTRA_CFLAGS" LDFLAGS="$EXTRA_LDFLAGS" ./configure --prefix=`pwd`/dist --disable-shared $EXTRA_FLAGS

    echo "Installing vpx for $ARCH..."
    make && make install

    echo "Installed: $DIR/dist"
    cd $SCRIPT_DIR
done
