#!/bin/sh

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common


if [ -d ffmpeg ]
then
    cd ffmpeg
    echo "Updating trunk..."
    svn update
    cd -
else
    echo "Pulling trunk..."
    svn co svn://svn.ffmpeg.org/ffmpeg/trunk ffmpeg
fi

for ARCH in $ARCHS
do


    FFMPEG_DIR=ffmpeg-$ARCH
    rm -rf $FFMPEG_DIR
    cp -a ffmpeg $FFMPEG_DIR

    cd $FFMPEG_DIR
    DIST_DIR=$DIST_DIR_BASE-$ARCH
    mkdir -p $DIST_DIR

    # Default configure options
    CONFIGURE_OPTIONS="--enable-gpl --enable-postproc --enable-swscale --enable-avfilter"

    # Use this to set your own configure-options
    if [ -f $SCRIPT_DIR/ffmpeg-conf ]
    then
        . $SCRIPT_DIR/ffmpeg-conf
    fi

    # Add x264 if exists
    if [ -d "$DIST_DIR/lib/libx264.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libx264"
    fi

    # Add xvid if exists
    if [ -d "$DIST_DIR/lib/libxvid.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libxvid"
    fi

    # Add vorbis if exists
    if [ -d "$DIST_DIR/lib/libvorbis.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libvorbis"
    fi

    # Add vpx if exists
    if [ -d "$DIST_DIR/lib/libvpx.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libvpx"
    fi

    # Add lame if exists
    if [ -d "$DIST_DIR/lib/libmp3lame.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libmp3lame"
    fi

    # Add speex if exists
    if [ -d "$DIST_DIR/lib/libspeex.a" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libspeex"
    fi


    # Use this to set your own build paths
    if [ -f $SCRIPT_DIR/build-local ]
    then
        . $SCRIPT_DIR/build-local
    fi

    CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --extra-ldflags=-L$DIST_DIR/lib --extra-cflags=-I$DIST_DIR/include"

    case $ARCH in
        armv6)
            EXTRA_FLAGS="--enable-cross-compile --target-os=darwin --arch=arm --cpu=arm1176jzf-s"
            EXTRA_CFLAGS="-arch $ARCH"
            EXTRA_LDFLAGS="-arch $ARCH"
            ;;
        armv7)
            EXTRA_FLAGS="--enable-cross-compile --target-os=darwin --arch=arm --cpu=cortex-a8 --enable-pic"
            EXTRA_CFLAGS="-arch $ARCH"
            EXTRA_LDFLAGS="-arch $ARCH"
            ;;
        i386)
            EXTRA_CC_FLAGS="-mdynamic-no-pic"
            ;;
    esac

    echo "Configure options: $CONFIGURE_OPTIONS"

    echo "Configuring ffmpeg for $ARCH..."
    ./configure --cc="$CC" --as="$SCRIPT_DIR/gas-preprocessor.pl $AS" --nm="$NM" --sysroot=$SYSROOT $EXTRA_FLAGS --extra-ldflags="$EXTRA_LDFLAGS" --extra-cflags="$EXTRA_CFLAGS" --prefix=$DIST_DIR $CONFIGURE_OPTIONS

    echo "Installing ffmpeg for $ARCH..."
    make && make install

    cd $SCRIPT_DIR

#    rm -rf $DIST_DIR/bin
#    rm -rf $DIST_DIR/share
done
