#!/bin/bash

DIR="xvid-$ARCH"

# Get xvid

cd $DIR
mkdir -p $DIR

cd build/generic/


case $ARCH in
    i386)
        CC=/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/i686-apple-darwin10-gcc-4.2.1
        SYSROOT=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.0.sdk
        ;;
    *)
        CC=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2
        SYSROOT=/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.0.sdk
        ;;
esac


FLAGS="-arch $ARCH -isysroot $SYSROOT"

CC=$CC LDFLAGS=$FLAGS CFLAGS=$FLAGS ./configure --prefix="dist" $EXTRA_FLAGS

make && make install

echo "Installed: $DIST_DIR"
