#!/bin/bash

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )
. $SCRIPT_DIR/build-common

# Get xvid
# TODO fill this in

for ARCH in $ARCHS
do

    DIR="xvidcore-$ARCH"
    rm -rf $DIR
    cp -a xvidcore $DIR

    cd $DIR
    DIST_DIR=$DIST_DIR_BASE-$ARCH
    mkdir -p $DIST_DIR

    cd build/generic/

    case $ARCH in
        armv6)
            EXTRA_FLAGS="--host=arm-apple-darwin"
            ;;
        armv7)
            EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic"
            ;;
        i386)
            EXTRA_FLAGS=""
            ;;
    esac

    FLAGS="-arch $ARCH -isysroot $SYSROOT"

    CC=$CC LDFLAGS=$FLAGS CFLAGS=$FLAGS ./configure --prefix=$DIST_DIR $EXTRA_FLAGS

    make && make install

    cd $SCRIPT_DIR
done
