#!/bin/sh

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common


echo "Pulling trunk..."
svn co svn://svn.ffmpeg.org/ffmpeg/trunk ffmpeg

for ARCH in $ARCHS
do

    FFMPEG_DIR=ffmpeg-$ARCH
    cp -a ffmpeg $FFMPEG_DIR

    cd $FFMPEG_DIR
    mkdir -p dist

    # Default configure options
    CONFIGURE_OPTIONS="--enable-gpl --enable-postproc --enable-swscale --enable-avfilter"

    # Use this to set your own configure-options
    if [ -f $SCRIPT_DIR/ffmpeg-conf ]
    then
        . $SCRIPT_DIR/ffmpeg-conf
    fi

    # Add x264 if exists
    X264_DIST="$SCRIPT_DIR/x264-$ARCH/dist"
    if [ -d "$X264_DIST" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libx264 --extra-ldflags=-L$X264_DIST/lib --extra-cflags=-I$X264_DIST/include"
    fi

    # Add xvid if exists
    XVID_DIST="$SCRIPT_DIR/xvid-$ARCH"
    if [ -d "$XVID_DIST" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libxvid --extra-ldflags=-L$XVID_DIST/lib --extra-cflags=-I$XVID_DIST/include"
    fi

#    OGG_DIST="$SCRIPT_DIR/ogg-$ARCH/dist"
    VORBIS_DIST="$SCRIPT_DIR/vorbis-$ARCH/dist"
    if [ -d "$VORBIS_DIST" ]; then
        #CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libvorbis --extra-ldflags=-L$VORBIS_DIST/lib --extra-ldflags=-L$OGG_DIST/lib --extra-cflags=-I$VORBIS_DIST/include --extra-cflags=-I$OGG_DIST/include "
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-libvorbis --extra-ldflags=-L$VORBIS_DIST/lib --extra-cflags=-I$VORBIS_DIST/include"
    fi


    # Use this to set your own build paths
    if [ -f $SCRIPT_DIR/build-local ]
    then
        . $SCRIPT_DIR/build-local
    fi

    case $ARCH in
        armv6)
            EXTRA_FLAGS="--enable-cross-compile --target-os=darwin --arch=arm --cpu=arm1176jzf-s"
            EXTRA_CFLAGS="-arch $ARCH"
            EXTRA_LDFLAGS="-arch $ARCH"
            ;;
        armv7)
            EXTRA_FLAGS="--enable-cross-compile --target-os=darwin --arch=arm --cpu=cortex-a8 --enable-pic"
            EXTRA_CFLAGS="-arch $ARCH"
            EXTRA_LDFLAGS="-arch $ARCH"
            ;;
        i386)
            EXTRA_CC_FLAGS="-mdynamic-no-pic"
            ;;
    esac

    echo "Configure options: $CONFIGURE_OPTIONS"

    ./configure --cc="$CC" --as="$SCRIPT_DIR/gas-preprocessor.pl $AS" --nm="$NM" --sysroot=$SYSROOT $EXTRA_FLAGS --extra-ldflags="$EXTRA_LDFLAGS" --extra-cflags="$EXTRA_CFLAGS" --prefix="dist" $CONFIGURE_OPTIONS

    make && make install

    echo "Installed: $FFMPEG_DIR/dist"
    cd $SCRIPT_DIR
done
