#!/bin/bash

set -e

SCRIPT_DIR=$( (cd -P $(dirname $0) && pwd) )

. $SCRIPT_DIR/build-common

git clone git://git.videolan.org/x264.git x264

for ARCH in $ARCHS
do

    DIR="x264-$ARCH"
    rm -rf $DIR
    cp -a x264 $DIR

    cd $DIR
    mkdir -p dist


    EXTRA_CFLAGS="-arch $ARCH"
    EXTRA_LDFLAGS="-arch $ARCH"
    case $ARCH in
        armv6)
            EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic --disable-asm"
            ;;
        armv7)
            EXTRA_FLAGS="--host=arm-apple-darwin --enable-pic"
            ;;
        i386)
            ;;
    esac

    echo "Configuring x264 for $ARCH..."
    CC=$CC ./configure $EXTRA_FLAGS --sysroot="$SYSROOT" --prefix='dist' --extra-cflags="$EXTRA_CFLAGS" --extra-ldflags="$EXTRA_LDFLAGS"

    echo "Installing x264 for $ARCH..."
    make && make install

    echo "Installed: $DIR/dist"
    cd $SCRIPT_DIR
done
